ASYNC_OBJS_DIR=../src/common
RPC_OBJS_DIR=../../fast-ipc-module/current/tests/rpc
CFLAGS_ipc.o = -O2 -DPOLL -fno-ipa-cp -fno-ipa-sra
CFLAGS_ring-channel.o = -I$(RPC_OBJS_DIR)../../IPC -fno-ipa-cp -fno-ipa-sra
EXTRA_CFLAGS=-DDEBUG_OUTPUT

obj-m := libasync.o
ccflags-y += -O0 -fno-ipa-cp -fno-ipa-sra -I$(LIBASYNC_DIR)/src/include -DUSE_ASYNC

libasync-objs = $(ASYNC_OBJS_DIR)/awe-mapper.o $(ASYNC_OBJS_DIR)/thc.o $(ASYNC_OBJS_DIR)/thcsync.o $(RPC_OBJS_DIR)/../../IPC/ipc.o $(RPC_OBJS_DIR)/../../ring-chan/ring-channel.o $(RPC_OBJS_DIR)/callee.o $(RPC_OBJS_DIR)/caller.o $(RPC_OBJS_DIR)/rpc_test.o
