OBJS_DIR=../src/common
obj-m := libasync.o
libasync-objs := $(OBJS_DIR)/main.o $(OBJS_DIR)/awe-mapper.o $(OBJS_DIR)/thc.o $(OBJS_DIR)/thcsync.o
ccflags-y += -fno-ipa-cp -fno-ipa-sra -I/local/sda4/xcap-async-module/libasync/src/include
